#ifndef __MyGUIform_main__
#define __MyGUIform_main__

/**
@file
Subclass of form_main, which is generated by wxFormBuilder.
*/

#include "MyGUI.h"

//// end generated include

/** Implementing form_main */
class MyGUIform_main : public form_main
{
	public:
		/** Constructor */
		MyGUIform_main( wxWindow* parent );
	//// end generated class members
	void e_button_1_click(wxCommandEvent& event);

};

#endif // __MyGUIform_main__
